const GET_COUNTRIES = "GET_COUNTRIES";
const SEARCH = "SEARCH";
const PAGE = "PAGE";
const INDEX = "INDEX";
const INDEX_BTN = "INDEX_BTN";
const LOADING = "LOADING";
const LOADING_DETAIL = "LOADING_DETAIL";

const RESET = "RESET";
const FILTER_POPULATION = "FILTER_POPULATION";
const FILTER_ALPH = "FILTER_ALPH";
const FILTER_CONTINENT = "FILTER_CONTINENT";

export {
  GET_COUNTRIES,
  SEARCH,
  PAGE,
  INDEX,
  INDEX_BTN,
  LOADING,
  LOADING_DETAIL,
  FILTER_POPULATION,
  FILTER_ALPH,
  FILTER_CONTINENT,
  RESET,
};
