const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRIES_NAME = "GET_COUNTRIES_NAME";
const FILTER_CONTINENT = "FILTER_CONTINENT";
const FILTER_POPULATION = "FILTER_POPULATION";
const FILTER_ALPH = "FILTER_ALPH";

export {
	GET_COUNTRIES, FILTER_ALPH, FILTER_POPULATION, FILTER_CONTINENT, GET_COUNTRIES_NAME
}