const GET_COUNTRIES = "GET_COUNTRIES";
const FILTER_CONTINENT = "FILTER_CONTINENT";
const FILTER_POPULATION = "FILTER_POPULATION";
const FILTER_ALPH = "FILTER_ALPH";

export {
	GET_COUNTRIES, FILTER_ALPH, FILTER_POPULATION, FILTER_CONTINENT
}